package pinpoint

import types "libds/aws/types"

type App struct {
	// Specifies settings for invoking an AWS Lambda function that customizes a segment for a campaign
	CampaignHook types.Pinpoint_AppCampaignHook `json:"campaignHook,omitempty" yaml:"campaignHook,omitempty"`

	// The default campaign limits for the app. These limits apply to each campaign for the app, unless the campaign overrides the default with limits of its own
	Limits types.Pinpoint_AppLimits `json:"limits,omitempty" yaml:"limits,omitempty"`

	// The application name. By default generated by Pulumi
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// The name of the Pinpoint application. Conflicts with `name`
	NamePrefix string `json:"namePrefix,omitempty" yaml:"namePrefix,omitempty"`

	// The default quiet time for the app. Each campaign for this app sends no messages during this time unless the campaign overrides the default with a quiet time of its own
	QuietTime types.Pinpoint_AppQuietTime `json:"quietTime,omitempty" yaml:"quietTime,omitempty"`

	// Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}
