package transfer

import types "libds/aws/types"

type Server struct {
	// The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM) certificate. This is required when `protocols` is set to `FTPS`
	Certificate string `json:"certificate,omitempty" yaml:"certificate,omitempty"`

	// Specifies the workflow details. See `workflow_details` Block below for details.
	WorkflowDetails types.Transfer_ServerWorkflowDetails `json:"workflowDetails,omitempty" yaml:"workflowDetails,omitempty"`

	// A map of tags to assign to the resource. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`

	// URL of the service endpoint used to authenticate users with an `identity_provider_type` of `API_GATEWAY`.
	Url string `json:"url,omitempty" yaml:"url,omitempty"`

	// The directory service ID of the directory service you want to connect to with an `identity_provider_type` of `AWS_DIRECTORY_SERVICE`.
	DirectoryId string `json:"directoryId,omitempty" yaml:"directoryId,omitempty"`

	// RSA, ECDSA, or ED25519 private key (e.g., as generated by the `ssh-keygen -t rsa -b 2048 -N "" -m PEM -f my-new-server-key`, `ssh-keygen -t ecdsa -b 256 -N "" -m PEM -f my-new-server-key` or `ssh-keygen -t ed25519 -N "" -f my-new-server-key` commands).
	HostKey string `json:"hostKey,omitempty" yaml:"hostKey,omitempty"`

	// Specifies whether or not performance for your Amazon S3 directories is optimized. This is disabled by default. See `s3_storage_options` Block below for details.
	S3StorageOptions types.Transfer_ServerS3StorageOptions `json:"s3StorageOptions,omitempty" yaml:"s3StorageOptions,omitempty"`

	// For SFTP-enabled servers, and for custom identity providers only. Valid values are `PASSWORD`, `PUBLIC_KEY`, `PUBLIC_KEY_OR_PASSWORD` and `PUBLIC_KEY_AND_PASSWORD`. Default value is: `PUBLIC_KEY_OR_PASSWORD`.
	SftpAuthenticationMethods string `json:"sftpAuthenticationMethods,omitempty" yaml:"sftpAuthenticationMethods,omitempty"`

	// A set of ARNs of destinations that will receive structured logs from the transfer server such as CloudWatch Log Group ARNs. If provided this enables the transfer server to emit structured logs to the specified locations.
	StructuredLogDestinations []string `json:"structuredLogDestinations,omitempty" yaml:"structuredLogDestinations,omitempty"`

	// The domain of the storage system that is used for file transfers. Valid values are: `S3` and `EFS`. The default value is `S3`.
	Domain string `json:"domain,omitempty" yaml:"domain,omitempty"`

	// The ARN for a lambda function to use for the Identity provider.
	Function string `json:"function,omitempty" yaml:"function,omitempty"`

	// The mode of authentication enabled for this service. The default value is `SERVICE_MANAGED`, which allows you to store and access SFTP user credentials within the service. `API_GATEWAY` indicates that user authentication requires a call to an API Gateway endpoint URL provided by you to integrate an identity provider of your choice. Using `AWS_DIRECTORY_SERVICE` will allow for authentication against AWS Managed Active Directory or Microsoft Active Directory in your on-premises environment, or in AWS using AD Connectors. Use the `AWS_LAMBDA` value to directly use a Lambda function as your identity provider. If you choose this value, you must specify the ARN for the lambda function in the `function` argument.
	IdentityProviderType string `json:"identityProviderType,omitempty" yaml:"identityProviderType,omitempty"`

	// Specify a string to display when users connect to a server. This string is displayed after the user authenticates. The SFTP protocol does not support post-authentication display banners.
	PostAuthenticationLoginBanner string `json:"postAuthenticationLoginBanner,omitempty" yaml:"postAuthenticationLoginBanner,omitempty"`

	// Specify a string to display when users connect to a server. This string is displayed before the user authenticates.
	PreAuthenticationLoginBanner string `json:"preAuthenticationLoginBanner,omitempty" yaml:"preAuthenticationLoginBanner,omitempty"`

	// The protocol settings that are configured for your server. See `protocol_details` Block below for details.
	ProtocolDetails types.Transfer_ServerProtocolDetails `json:"protocolDetails,omitempty" yaml:"protocolDetails,omitempty"`

	// The virtual private cloud (VPC) endpoint settings that you want to configure for your SFTP server. See `endpoint_details` Block below for details.
	EndpointDetails types.Transfer_ServerEndpointDetails `json:"endpointDetails,omitempty" yaml:"endpointDetails,omitempty"`

	// The type of endpoint that you want your SFTP server connect to. If you connect to a `VPC` (or `VPC_ENDPOINT`), your SFTP server isn't accessible over the public internet. If you want to connect your SFTP server via public internet, set `PUBLIC`.  Defaults to `PUBLIC`.
	EndpointType string `json:"endpointType,omitempty" yaml:"endpointType,omitempty"`

	// A boolean that indicates all users associated with the server should be deleted so that the Server can be destroyed without error. The default value is `false`. This option only applies to servers configured with a `SERVICE_MANAGED` `identity_provider_type`.
	ForceDestroy bool `json:"forceDestroy,omitempty" yaml:"forceDestroy,omitempty"`

	// Amazon Resource Name (ARN) of the IAM role used to authenticate the user account with an `identity_provider_type` of `API_GATEWAY`.
	InvocationRole string `json:"invocationRole,omitempty" yaml:"invocationRole,omitempty"`

	// Amazon Resource Name (ARN) of an IAM role that allows the service to write your SFTP users’ activity to your Amazon CloudWatch logs for monitoring and auditing purposes.
	LoggingRole string `json:"loggingRole,omitempty" yaml:"loggingRole,omitempty"`

	/*
	   Specifies the file transfer protocol or protocols over which your file transfer protocol client can connect to your server's endpoint. This defaults to `SFTP` . The available protocols are:
	   - `AS2`: File transfer over Applicability Statement 2
	   - `SFTP`: File transfer over SSH
	   - `FTPS`: File transfer with TLS encryption
	   - `FTP`: Unencrypted file transfer
	*/
	Protocols []string `json:"protocols,omitempty" yaml:"protocols,omitempty"`

	/*
	   Specifies the name of the security policy that is attached to the server. Default value is: `TransferSecurityPolicy-2018-11`. The available values are:
	   - `TransferSecurityPolicy-2018-11`
	   - `TransferSecurityPolicy-2020-06`
	   - `TransferSecurityPolicy-2022-03`
	   - `TransferSecurityPolicy-2023-05`
	   - `TransferSecurityPolicy-2024-01`
	   - `TransferSecurityPolicy-FIPS-2020-06`
	   - `TransferSecurityPolicy-FIPS-2023-05`
	   - `TransferSecurityPolicy-FIPS-2024-01`
	   - `TransferSecurityPolicy-FIPS-2024-05`
	   - `TransferSecurityPolicy-PQ-SSH-Experimental-2023-04`
	   - `TransferSecurityPolicy-PQ-SSH-FIPS-Experimental-2023-04`
	   - `TransferSecurityPolicy-Restricted-2018-11`
	   - `TransferSecurityPolicy-Restricted-2020-06`

	   See [Security policies for AWS Transfer Family servers](https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html) for details.
	*/
	SecurityPolicyName string `json:"securityPolicyName,omitempty" yaml:"securityPolicyName,omitempty"`
}
