package cloudfront

type PublicKey struct {
	// The encoded public key that you want to add to CloudFront to use with features like field-level encryption.
	EncodedKey string `json:"encodedKey,omitempty" yaml:"encodedKey,omitempty"`

	// The name for the public key. By default generated by this provider. Note: Do not set if using the key's id in another resource (e.g. KeyGroup) since it will result in a dependency error from AWS. Instead, it is recommended to use Pulumi autonaming by leaving this property unset (default behavior) or set the `namePrefix` property to allow the provider to autoname the resource.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	/*
	   The name for the public key. Conflicts with `name`.

	   --NOTE:-- When setting `encoded_key` value, there needs a newline at the end of string. Otherwise, multiple runs of pulumi will want to recreate the `aws.cloudfront.PublicKey` resource.
	*/
	NamePrefix string `json:"namePrefix,omitempty" yaml:"namePrefix,omitempty"`

	// An optional comment about the public key.
	Comment string `json:"comment,omitempty" yaml:"comment,omitempty"`
}
