package iam

type SamlProvider struct {
	// The name of the provider to create.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// An XML document generated by an identity provider that supports SAML 2.0.
	SamlMetadataDocument string `json:"samlMetadataDocument,omitempty" yaml:"samlMetadataDocument,omitempty"`

	// Map of resource tags for the IAM SAML provider. .If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}
