package types

type Apigateway_ApiConfigGrpcService struct {
	/*
	   Input only. File descriptor set, generated by protoc.
	   To generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.
	   $ protoc --include_imports --include_source_info test.proto -o out.pb
	   Structure is documented below.
	*/
	FileDescriptorSet Apigateway_ApiConfigGrpcServiceFileDescriptorSet `json:"fileDescriptorSet,omitempty" yaml:"fileDescriptorSet,omitempty"`

	/*
	   Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.
	   Structure is documented below.
	*/
	Sources []Apigateway_ApiConfigGrpcServiceSource `json:"sources,omitempty" yaml:"sources,omitempty"`
}
