package types

type Cloudrun_getServiceTemplateMetadata struct {
	/*
	   An opaque value that represents the internal version of this object that
	   can be used by clients to determine when objects have changed. May be used
	   for optimistic concurrency, change detection, and the watch operation on a
	   resource or set of resources. They may only be valid for a
	   particular resource or set of resources.
	*/
	ResourceVersion string `json:"resourceVersion,omitempty" yaml:"resourceVersion,omitempty"`

	// SelfLink is a URL representing this object.
	SelfLink string `json:"selfLink,omitempty" yaml:"selfLink,omitempty"`

	/*
	   UID is a unique id generated by the server on successful creation of a resource and is not
	   allowed to change on PUT operations.
	*/
	Uid string `json:"uid,omitempty" yaml:"uid,omitempty"`

	//
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`

	// A sequence number representing a specific generation of the desired state.
	Generation int `json:"generation,omitempty" yaml:"generation,omitempty"`

	/*
	   Map of string keys and values that can be used to organize and categorize
	   (scope and select) objects.
	*/
	Labels map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`

	// The name of the Cloud Run Service.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	/*
	   In Cloud Run the namespace must be equal to either the
	   project ID or project number. It will default to the resource's project.
	*/
	Namespace string `json:"namespace,omitempty" yaml:"namespace,omitempty"`
}
