package types

type Cloudrun_getServiceTemplate struct {
	/*
	   Optional metadata for this Revision, including labels and annotations.
	   Name will be generated by the Configuration. To set minimum instances
	   for this revision, use the "autoscaling.knative.dev/minScale" annotation
	   key. To set maximum instances for this revision, use the
	   "autoscaling.knative.dev/maxScale" annotation key. To set Cloud SQL
	   connections for the revision, use the "run.googleapis.com/cloudsql-instances"
	   annotation key.
	*/
	Metadatas []Cloudrun_getServiceTemplateMetadata `json:"metadatas,omitempty" yaml:"metadatas,omitempty"`

	// RevisionSpec holds the desired state of the Revision (from the client).
	Specs []Cloudrun_getServiceTemplateSpec `json:"specs,omitempty" yaml:"specs,omitempty"`
}
