package types

type Dataproc_JobPlacement struct {
	// The name of the cluster where the job will be submitted
	ClusterName string `json:"clusterName,omitempty" yaml:"clusterName,omitempty"`

	// Output-only. A cluster UUID generated by the Cloud Dataproc service when the job is submitted
	ClusterUuid string `json:"clusterUuid,omitempty" yaml:"clusterUuid,omitempty"`
}
