package billing

type AccountIamPolicy struct {
	/*
	   The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

	   - - -
	*/
	PolicyData string `json:"policyData,omitempty" yaml:"policyData,omitempty"`

	/*
	   The billing account id.

	   For `gcp.billing.AccountIamMember` or `gcp.billing.AccountIamBinding`:

	   - `member/members` - (Required) Identities that will be granted the privilege in `role`.
	   Each entry can have one of the following values:
	   - --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
	   - --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
	   - --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
	   - --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
	*/
	BillingAccountId string `json:"billingAccountId,omitempty" yaml:"billingAccountId,omitempty"`
}
