package efs

import types "libds/aws/types"

type FileSystem struct {
	// If true, the disk will be encrypted.
	Encrypted bool `json:"encrypted,omitempty" yaml:"encrypted,omitempty"`

	// The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true.
	KmsKeyId string `json:"kmsKeyId,omitempty" yaml:"kmsKeyId,omitempty"`

	// The file system performance mode. Can be either `"generalPurpose"` or `"maxIO"` (Default: `"generalPurpose"`).
	PerformanceMode string `json:"performanceMode,omitempty" yaml:"performanceMode,omitempty"`

	// The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`.
	ProvisionedThroughputInMibps float64 `json:"provisionedThroughputInMibps,omitempty" yaml:"provisionedThroughputInMibps,omitempty"`

	// Throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `provisioned`, or `elastic`. When using `provisioned`, also set `provisioned_throughput_in_mibps`.
	ThroughputMode string `json:"throughputMode,omitempty" yaml:"throughputMode,omitempty"`

	// the AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes. See [user guide](https://docs.aws.amazon.com/efs/latest/ug/availability-durability.html) for more information.
	AvailabilityZoneName string `json:"availabilityZoneName,omitempty" yaml:"availabilityZoneName,omitempty"`

	/*
	   A unique name (a maximum of 64 characters are allowed)
	   used as reference when creating the Elastic File System to ensure idempotent file
	   system creation. By default generated by this provider. See [Elastic File System]
	   user guide for more information.
	*/
	CreationToken string `json:"creationToken,omitempty" yaml:"creationToken,omitempty"`

	// A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object. See `lifecycle_policy` block below for details.
	LifecyclePolicies []types.Efs_FileSystemLifecyclePolicy `json:"lifecyclePolicies,omitempty" yaml:"lifecyclePolicies,omitempty"`

	// A file system [protection](https://docs.aws.amazon.com/efs/latest/ug/API_FileSystemProtectionDescription.html) object. See `protection` block below for details.
	Protection types.Efs_FileSystemProtection `json:"protection,omitempty" yaml:"protection,omitempty"`

	// A map of tags to assign to the file system. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}
