package types

type Cloudbuild_TriggerBitbucketServerTriggerConfig struct {
	// Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is "TEST".
	ProjectKey string `json:"projectKey,omitempty" yaml:"projectKey,omitempty"`

	/*
	   Filter to match changes in pull requests.
	   Structure is documented below.
	*/
	PullRequest Cloudbuild_TriggerBitbucketServerTriggerConfigPullRequest `json:"pullRequest,omitempty" yaml:"pullRequest,omitempty"`

	/*
	   Filter to match changes in refs like branches, tags.
	   Structure is documented below.
	*/
	Push Cloudbuild_TriggerBitbucketServerTriggerConfigPush `json:"push,omitempty" yaml:"push,omitempty"`

	/*
	   Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.
	   For example, if the repository name is 'test repo', in the URL it would become 'test-repo' as in https://mybitbucket.server/projects/TEST/repos/test-repo.
	*/
	RepoSlug string `json:"repoSlug,omitempty" yaml:"repoSlug,omitempty"`

	// The Bitbucket server config resource that this trigger config maps to.
	BitbucketServerConfigResource string `json:"bitbucketServerConfigResource,omitempty" yaml:"bitbucketServerConfigResource,omitempty"`
}
