package types

type Cloudrun_getServiceMetadata struct {
	// A sequence number representing a specific generation of the desired state.
	Generation int `json:"generation,omitempty" yaml:"generation,omitempty"`

	/*
	   Map of string keys and values that can be used to organize and categorize
	   (scope and select) objects. May match selectors of replication controllers
	   and routes.

	   --Note--: This field is non-authoritative, and will only manage the labels present in your configuration.
	   Please refer to the field 'effective_labels' for all of the labels present on the resource.
	*/
	Labels map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`

	/*
	   In Cloud Run the namespace must be equal to either the
	   project ID or project number.
	*/
	Namespace string `json:"namespace,omitempty" yaml:"namespace,omitempty"`

	/*
	   The combination of labels configured directly on the resource
	    and default labels configured on the provider.
	*/
	PulumiLabels map[string]string `json:"pulumiLabels,omitempty" yaml:"pulumiLabels,omitempty"`

	/*
	   An opaque value that represents the internal version of this object that
	   can be used by clients to determine when objects have changed. May be used
	   for optimistic concurrency, change detection, and the watch operation on a
	   resource or set of resources. They may only be valid for a
	   particular resource or set of resources.
	*/
	ResourceVersion string `json:"resourceVersion,omitempty" yaml:"resourceVersion,omitempty"`

	/*
	   UID is a unique id generated by the server on successful creation of a resource and is not
	   allowed to change on PUT operations.
	*/
	Uid string `json:"uid,omitempty" yaml:"uid,omitempty"`

	//
	Annotations map[string]string `json:"annotations,omitempty" yaml:"annotations,omitempty"`

	//
	EffectiveAnnotations map[string]string `json:"effectiveAnnotations,omitempty" yaml:"effectiveAnnotations,omitempty"`

	//
	EffectiveLabels map[string]string `json:"effectiveLabels,omitempty" yaml:"effectiveLabels,omitempty"`

	// SelfLink is a URL representing this object.
	SelfLink string `json:"selfLink,omitempty" yaml:"selfLink,omitempty"`
}
