package types

type Cloudrun_ServiceTemplate struct {
	/*
	   Optional metadata for this Revision, including labels and annotations.
	   Name will be generated by the Configuration. To set minimum instances
	   for this revision, use the "autoscaling.knative.dev/minScale" annotation
	   key. To set maximum instances for this revision, use the
	   "autoscaling.knative.dev/maxScale" annotation key. To set Cloud SQL
	   connections for the revision, use the "run.googleapis.com/cloudsql-instances"
	   annotation key.
	   Structure is documented below.
	*/
	Metadata Cloudrun_ServiceTemplateMetadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	/*
	   RevisionSpec holds the desired state of the Revision (from the client).
	   Structure is documented below.
	*/
	Spec Cloudrun_ServiceTemplateSpec `json:"spec,omitempty" yaml:"spec,omitempty"`
}
