package types

type Dataproc_JobReference struct {
	// The job ID, which must be unique within the project. The job ID is generated by the server upon job submission or provided by the user as a means to perform retries without creating duplicate jobs
	JobId string `json:"jobId,omitempty" yaml:"jobId,omitempty"`
}
