package types

type Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfig struct {
	/*
	   Custom output properties. A set of optional name-value pairs that define custom source properties to
	   return with each finding that is generated by the custom module. The custom
	   source properties that are defined here are included in the finding JSON
	   under `sourceProperties`.
	   Structure is documented below.
	*/
	CustomOutput Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigCustomOutput `json:"customOutput,omitempty" yaml:"customOutput,omitempty"`

	/*
	   Text that describes the vulnerability or misconfiguration that the custom
	   module detects.
	*/
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	/*
	   The CEL expression to evaluate to produce findings.When the expression
	   evaluates to true against a resource, a finding is generated.
	   Structure is documented below.
	*/
	Predicate Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigPredicate `json:"predicate,omitempty" yaml:"predicate,omitempty"`

	/*
	   An explanation of the recommended steps that security teams can take to
	   resolve the detected issue
	*/
	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`

	/*
	   The resource types that the custom module operates on. Each custom module
	   can specify up to 5 resource
	   Structure is documented below.
	*/
	ResourceSelector Securityposture_PosturePolicySetPolicyConstraintSecurityHealthAnalyticsCustomModuleConfigResourceSelector `json:"resourceSelector,omitempty" yaml:"resourceSelector,omitempty"`

	/*
	   The severity to assign to findings generated by the module.
	   Possible values are: `SEVERITY_UNSPECIFIED`, `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`.
	*/
	Severity string `json:"severity,omitempty" yaml:"severity,omitempty"`
}
