package dataproc

type ClusterIAMPolicy struct {
	/*
	   The project in which the cluster belongs. If it
	   is not provided, the provider will use a default.
	*/
	Project string `json:"project,omitempty" yaml:"project,omitempty"`

	/*
	   The region in which the cluster belongs. If it
	   is not provided, the provider will use a default.
	*/
	Region string `json:"region,omitempty" yaml:"region,omitempty"`

	/*
	   The name or relative resource id of the cluster to manage IAM policies for.

	   For `gcp.dataproc.ClusterIAMMember` or `gcp.dataproc.ClusterIAMBinding`:

	   - `member/members` - (Required) Identities that will be granted the privilege in `role`.
	   Each entry can have one of the following values:
	   - --allUsers--: A special identifier that represents anyone who is on the internet; with or without a Google account.
	   - --allAuthenticatedUsers--: A special identifier that represents anyone who is authenticated with a Google account or a service account.
	   - --user:{emailid}--: An email address that represents a specific Google account. For example, alice@gmail.com or joe@example.com.
	   - --serviceAccount:{emailid}--: An email address that represents a service account. For example, my-other-app@appspot.gserviceaccount.com.
	   - --group:{emailid}--: An email address that represents a Google group. For example, admins@example.com.
	   - --domain:{domain}--: A G Suite domain (primary, instead of alias) name that represents all the users of that domain. For example, google.com or example.com.
	*/
	Cluster string `json:"cluster,omitempty" yaml:"cluster,omitempty"`

	/*
	   The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

	   - - -
	*/
	PolicyData string `json:"policyData,omitempty" yaml:"policyData,omitempty"`
}
