package dataproc

type JobIAMPolicy struct {
	/*
	   The policy data generated by a `gcp.organizations.getIAMPolicy` data source.

	   - - -
	*/
	PolicyData string `json:"policyData,omitempty" yaml:"policyData,omitempty"`

	/*
	   The project in which the job belongs. If it
	   is not provided, the provider will use a default.
	*/
	Project string `json:"project,omitempty" yaml:"project,omitempty"`

	/*
	   The region in which the job belongs. If it
	   is not provided, the provider will use a default.
	*/
	Region string `json:"region,omitempty" yaml:"region,omitempty"`

	//
	JobId string `json:"jobId,omitempty" yaml:"jobId,omitempty"`
}
