package emr

type SecurityConfiguration struct {
	// A JSON formatted Security Configuration
	Configuration string `json:"configuration,omitempty" yaml:"configuration,omitempty"`

	// The name of the EMR Security Configuration. By default generated by this provider.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	/*
	   Creates a unique name beginning with the specified
	   prefix. Conflicts with `name`.
	*/
	NamePrefix string `json:"namePrefix,omitempty" yaml:"namePrefix,omitempty"`
}
