package cloudwatch

type EventApiDestination struct {
	// Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc.
	HttpMethod string `json:"httpMethod,omitempty" yaml:"httpMethod,omitempty"`

	// URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include "-" as path parameters wildcards to be set from the Target HttpParameters.
	InvocationEndpoint string `json:"invocationEndpoint,omitempty" yaml:"invocationEndpoint,omitempty"`

	// Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300).
	InvocationRateLimitPerSecond int `json:"invocationRateLimitPerSecond,omitempty" yaml:"invocationRateLimitPerSecond,omitempty"`

	// The name of the new API Destination. The name must be unique for your account. Maximum of 64 characters consisting of numbers, lower/upper case letters, .,-,_.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// ARN of the EventBridge Connection to use for the API Destination.
	ConnectionArn string `json:"connectionArn,omitempty" yaml:"connectionArn,omitempty"`

	// The description of the new API Destination. Maximum of 512 characters.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}
