package types

type Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH264SettingsFilterSettings struct {
	// Temporal filter settings. See Temporal Filter Settings
	TemporalFilterSettings Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH264SettingsFilterSettingsTemporalFilterSettings `json:"temporalFilterSettings,omitempty" yaml:"temporalFilterSettings,omitempty"`
}
