package securitylake

import types "DesignSphere_Server/src/resource/aws/types"

type DataLake struct {
	// Specify the Region or Regions that will contribute data to the rollup region.
	Configuration types.Securitylake_DataLakeConfiguration `json:"configuration,omitempty" yaml:"configuration,omitempty"`

	// The Amazon Resource Name (ARN) used to create and update the AWS Glue table. This table contains partitions generated by the ingestion and normalization of AWS log sources and custom sources.
	MetaStoreManagerRoleArn string `json:"metaStoreManagerRoleArn,omitempty" yaml:"metaStoreManagerRoleArn,omitempty"`

	// Key-value map of resource tags. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`

	//
	Timeouts types.Securitylake_DataLakeTimeouts `json:"timeouts,omitempty" yaml:"timeouts,omitempty"`
}
