package signer

type SigningProfilePermission struct {
	// A statement identifier prefix. The provider will generate a unique suffix. Conflicts with `statement_id`.
	StatementIdPrefix string `json:"statementIdPrefix,omitempty" yaml:"statementIdPrefix,omitempty"`

	// An AWS Signer action permitted as part of cross-account permissions. Valid values: `signer:StartSigningJob`, `signer:GetSigningProfile`, `signer:RevokeSignature`, or `signer:SignPayload`.
	Action string `json:"action,omitempty" yaml:"action,omitempty"`

	// The AWS principal to be granted a cross-account permission.
	Principal string `json:"principal,omitempty" yaml:"principal,omitempty"`

	// Name of the signing profile to add the cross-account permissions.
	ProfileName string `json:"profileName,omitempty" yaml:"profileName,omitempty"`

	// The signing profile version that a permission applies to.
	ProfileVersion string `json:"profileVersion,omitempty" yaml:"profileVersion,omitempty"`

	// A unique statement identifier. By default generated by the provider.
	StatementId string `json:"statementId,omitempty" yaml:"statementId,omitempty"`
}
