package signer

import types "DesignSphere_Server/src/resource/aws/types"

type SigningProfile struct {
	// A unique signing profile name. By default generated by the provider. Signing profile names are immutable and cannot be reused after canceled.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// A signing profile name prefix. The provider will generate a unique suffix. Conflicts with `name`.
	NamePrefix string `json:"namePrefix,omitempty" yaml:"namePrefix,omitempty"`

	// The ID of the platform that is used by the target signing profile.
	PlatformId string `json:"platformId,omitempty" yaml:"platformId,omitempty"`

	// The validity period for a signing job.
	SignatureValidityPeriod types.Signer_SigningProfileSignatureValidityPeriod `json:"signatureValidityPeriod,omitempty" yaml:"signatureValidityPeriod,omitempty"`

	//
	SigningMaterial types.Signer_SigningProfileSigningMaterial `json:"signingMaterial,omitempty" yaml:"signingMaterial,omitempty"`

	// A list of tags associated with the signing profile. If configured with a provider `default_tags` configuration block present, tags with matching keys will overwrite those defined at the provider-level.
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}
