package endpoints

type ConsumersIamPolicy struct {
	//
	ConsumerProject string `json:"consumerProject,omitempty" yaml:"consumerProject,omitempty"`

	/*
	   The policy data generated by
	   a `gcp.organizations.getIAMPolicy` data source.
	*/
	PolicyData string `json:"policyData,omitempty" yaml:"policyData,omitempty"`

	//
	ServiceName string `json:"serviceName,omitempty" yaml:"serviceName,omitempty"`
}
