package types

type Lex_V2modelsSlotSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecification struct {
	//
	DefaultValueLists []Lex_V2modelsSlotSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecificationDefaultValueList `json:"defaultValueLists,omitempty" yaml:"defaultValueLists,omitempty"`
}
