package types

type Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH265SettingsFilterSettings struct {
	//
	TemporalFilterSettings Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH265SettingsFilterSettingsTemporalFilterSettings `json:"temporalFilterSettings,omitempty" yaml:"temporalFilterSettings,omitempty"`
}
