package types

type Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH264SettingsFilterSettings struct {
	//
	TemporalFilterSettings Medialive_ChannelEncoderSettingsVideoDescriptionCodecSettingsH264SettingsFilterSettingsTemporalFilterSettings `json:"temporalFilterSettings,omitempty" yaml:"temporalFilterSettings,omitempty"`
}
