package types

type Networkfirewall_getFirewallPolicyFirewallPolicyStatelessCustomActionActionDefinitionPublishMetricAction struct {
	//
	Dimensions []Networkfirewall_getFirewallPolicyFirewallPolicyStatelessCustomActionActionDefinitionPublishMetricActionDimension `json:"dimensions,omitempty" yaml:"dimensions,omitempty"`
}
