package types

type Sagemaker_UserProfileUserSettingsCanvasAppSettingsWorkspaceSettings struct {
	// The Amazon S3 bucket used to store artifacts generated by Canvas. Updating the Amazon S3 location impacts existing configuration settings, and Canvas users no longer have access to their artifacts. Canvas users must log out and log back in to apply the new location.
	S3ArtifactPath string `json:"s3ArtifactPath,omitempty" yaml:"s3ArtifactPath,omitempty"`

	// The Amazon Web Services Key Management Service (KMS) encryption key ID that is used to encrypt artifacts generated by Canvas in the Amazon S3 bucket.
	S3KmsKeyId string `json:"s3KmsKeyId,omitempty" yaml:"s3KmsKeyId,omitempty"`
}
